import Head from "next/head";
import { useRouter } from "next/router";

export default function Header() {
  const router = useRouter();

  return (
    <header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex justify-between p-3 border-b">
        <h1 className="select-none text-lg cursor-pointer font-semibold tracking-wider">
          Daybook
        </h1>

        <ul className="flex items-center gap-3 capitalize">
          <li
            className="cursor-pointer"
            onClick={() => router.push("/auth/sign-in")}
          >
            sign in
          </li>
          <li
            className="cursor-pointer"
            onClick={() => router.push("/auth/sign-up")}
          >
            sign up
          </li>
        </ul>
      </section>
    </header>
  );
}
